# permissions for end users to view killoldpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: killoldpod-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: killoldpod-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - killoldpods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - killoldpods/status
  verbs:
  - get
